# IProvider interface
from typing import List, Optional, Dict
from models.block import Block
from models.tx import Tx

class IProvider:
    def latest_block_number(self) -> int: ...
    def recent_blocks(self, n: int = 10) -> List[Block]: ...
    def recent_txs(self, n: int = 20) -> List[Tx]: ...
    def get_block(self, number: int) -> Optional[Block]: ...
    def get_tx(self, h: str) -> Optional[Tx]: ...
    def get_address(self, addr: str) -> Dict: ...
    def avg_block_time(self, k: int = 20) -> float: ...
    def tps(self, k: int = 20) -> float: ...
    def mempool_size(self) -> int: ...

